FROM local/centos7-systemd

ARG SCENARIO_PATH
ARG SERVICE_A_EXIT_CODE

COPY ./$SCENARIO_PATH/a.service /usr/lib/systemd/system/a.service
COPY ./$SCENARIO_PATH/b.service /usr/lib/systemd/system/b.service
COPY ./files/journald.conf /etc/systemd/journald.conf
COPY ./files/write-exit-code.sh /tmp/write-exit-code.sh

RUN mkdir /usr/lib/systemd/system/a.service.d/
RUN /tmp/write-exit-code.sh ${SERVICE_A_EXIT_CODE}

RUN systemctl enable a
RUN systemctl enable b

CMD ["/usr/sbin/init"]
